[pytest]
norecursedirs = env/*
addopts = -p no:cacheprovider
testpaths = tests/
python_files = test_*.py
timeout = 2
filterwarnings =
    ignore:The 'warn' function is deprecated, use 'warning' instead:DeprecationWarning
